version: "3"
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DigitalVault123
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  fastapi:
    container_name: fastapi
    build:
      context: ./backend
    # development mode
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  flask:
    container_name: flask
    build:
      context: ./frontend
    restart: always
    depends_on:
      - fastapi
    expose:
      - 5000
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - fastapi
      - flask
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
