version: "3"
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5.8
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DigitalVault123
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  fastapi:
    container_name: fastapi
    build:
      context: ./backend
    restart: always
    depends_on:
      - mariadb
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:DigitalVault123@mariadb/CloudPass
    ports:
      - 8000:8000
    networks:
      - mynetwork

  flask:
    container_name: flask
    build:
      context: ./frontend
    restart: always
    depends_on:
      - fastapi
    expose:
      - 5000
    networks:
      - mynetwork

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - fastapi
      - flask
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
