version: "3"
services:
  db:
    image: mysql:8.0
    restart: "no"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - app-db-data:/var/lib/mysql
    networks:
      - main

  adminer:
    image: adminer
    restart: "no"
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    networks:
      - main

  backend:
    restart: "no"
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PROJECT_NAME=${PROJECT_NAME}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    platform: linux/amd64
    volumes:
      - ./backend:/app
    command: /start-reload.sh
    depends_on:
      - db
    networks:
      - main

  nginx:
    restart: "no"
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - backend
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - main

volumes:
  app-db-data:

networks:
  main:
