name: fullstack
services:
  backend:
    build:
      context: /home/brandon/Dropbox/Developer/boilerplates/fullstack/backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_started
        required: true
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    environment:
      BACKEND_INSTANCES: "1"
      DATABASE_URL: mysql+pymysql://mysql:changethis@mysql:3306/fullstack
      DOMAIN: localhost
      ENVIRONMENT: local
      MYSQL_DATABASE: fullstack
      MYSQL_PASSWORD: changethis
      MYSQL_ROOT_PASSWORD: changethis
      MYSQL_USER: mysql
      PROJECT_NAME: Full Stack Boilerplate
      SECRET_KEY: changethis
      STACK_NAME: full-stack-boilerplate
    networks:
      main: null
    platform: linux/amd64
    restart: always
  mysql:
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      BACKEND_INSTANCES: "1"
      DOMAIN: localhost
      ENVIRONMENT: local
      MYSQL_DATABASE: fullstack
      MYSQL_PASSWORD: changethis
      MYSQL_ROOT_PASSWORD: changethis
      MYSQL_USER: mysql
      PROJECT_NAME: Full Stack Boilerplate
      SECRET_KEY: changethis
      STACK_NAME: full-stack-boilerplate
    image: mysql:8.0
    networks:
      main: null
    restart: always
    volumes:
      - type: volume
        source: app-db-data
        target: /var/lib/mysql
        volume: {}
  nginx:
    depends_on:
      backend:
        condition: service_started
        required: true
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      DOMAIN: localhost
    image: nginx
    networks:
      main: null
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /home/brandon/Dropbox/Developer/boilerplates/fullstack/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        bind:
          create_host_path: true
networks:
  main:
    name: fullstack_main
volumes:
  app-db-data:
    name: fullstack_app-db-data
